name = "PhaseBases"
uuid = "c4d961ba-0ec2-4b0f-a161-22c1127deb0e"
authors = ["Oleg Soloviev"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SampledDomains = "a82262f3-35bb-4fed-9e1b-5653a3e90076"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ZChop = "8603256b-76ad-53fe-b511-38a38e6437cd"

[compat]
FFTW = "1.10.0"
Statistics = "1.11.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
